force-app/main/default/objects/CaseUpdate__c/CaseUpdate__c.object-meta.xml
<CustomObject>
    <label>Case Update</label>
    <nameField>
        <label>Case Update</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseUpdate__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Updates</relationshipLabel>
    <relationshipName>Case_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseUpdate__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <label>Summary</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CaseUpdate__c/fields/UpdateType__c.field-meta.xml
<CustomField>
    <fullName>UpdateType__c</fullName>
    <label>Update Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Note</fullName>
            </value>
            <value>
                <fullName>CustomerContacted</fullName>
                <label>Customer Contacted</label>
            </value>
            <value>
                <fullName>InternalInvestigation</fullName>
                <label>Internal Investigation</label>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Resolution</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseUpdate__c/fields/VisibleToCustomer__c.field-meta.xml
<CustomField>
    <fullName>VisibleToCustomer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CasesUpdatesSelector.cls
public virtual class CasesUpdatesSelector extends fflib_SObjectSelector {

    public static CasesUpdatesSelector newInstance() {
        return (CasesUpdatesSelector) SFDC_Application.Selector.newInstance(CaseUpdate__c.getSObjectType());
    }

    public Schema.SObjectType getSObjectType() {
        return CaseUpdate__c.SObjectType;
    }

    public virtual List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            CaseUpdate__c.Id, 
            CaseUpdate__c.Case__c, 
            CaseUpdate__c.CreatedDate,
            CaseUpdate__c.UpdateType__c, 
            CaseUpdate__c.Summary__c, 
            CaseUpdate__c.VisibleToCustomer__c
        };
    }

    public List<CaseUpdate__c> selectRecentByCaseIds(Set<Id> caseIds, Integer limitSize) {
        if (caseIds == null || caseIds.isEmpty()) return new List<CaseUpdate__c>();

        if (limitSize == null || limitSize <= 0) limitSize = 5;

        fflib_QueryFactory qf = newQueryFactory();
        qf.selectField('CreatedBy.Name');
        qf.setCondition('Case__c IN :caseIds');
        qf.addOrdering(CaseUpdate__c.CreatedDate, fflib_QueryFactory.SortOrder.DESCENDING);
        qf.setLimit(limitSize);

        return (List<CaseUpdate__c>) Database.query(qf.toSOQL());
    }
}